version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    image: mysql:5.7
    container_name: pet_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pet_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
